services:
  - type: web
    name: enterprise-hrms
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production

