<?php

namespace App\Controllers;

use CodeIgniter\HTTP\ResponseInterface;

/**
 * Class BackupController
 *
 * Module 44: Database Backup, Recovery & Export Center
 */
class BackupController extends BaseController
{
    /**
     * Backup Dashboard & Health Overview
     */
    public function index()
    {
        if (!$this->hasRole(['super_admin', 'hr_admin'])) {
            $this->session->setFlashdata('error', 'Access Denied: Only Super Administrators can manage database backups.');
            return redirect()->to(site_url('dashboard'));
        }

        $db = \Config\Database::connect();
        $dbName = $db->database;

        // Query database table information
        $tablesData = $db->query("
            SELECT 
                TABLE_NAME AS table_name,
                TABLE_ROWS AS row_count,
                DATA_LENGTH AS data_length,
                INDEX_LENGTH AS index_length,
                CREATE_TIME AS create_time,
                UPDATE_TIME AS update_time
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = ?
            ORDER BY TABLE_NAME ASC
        ", [$dbName])->getResultArray();

        $totalSize = 0;
        $totalRows = 0;
        foreach ($tablesData as $t) {
            $totalSize += ((float)$t['data_length'] + (float)$t['index_length']);
            $totalRows += (int)$t['row_count'];
        }

        $totalSizeMB = round($totalSize / (1024 * 1024), 2);

        // Fetch recent backup audit entries
        $recentBackups = $db->table('activity_logs')
            ->where('action', 'DATABASE_BACKUP')
            ->orderBy('id', 'DESC')
            ->limit(10)
            ->get()
            ->getResultArray();

        $data = [
            'dbName'        => $dbName,
            'tables'        => $tablesData,
            'tableCount'    => count($tablesData),
            'totalRows'     => $totalRows,
            'totalSizeMB'   => $totalSizeMB,
            'recentBackups' => $recentBackups,
            'mysqlVersion'  => $db->getVersion(),
        ];

        return $this->render('settings/backup', $data, 'Database Backup & System Recovery');
    }

    /**
     * Generate & Download Full MySQL Database Dump (.sql)
     */
    public function exportDatabase(): ResponseInterface
    {
        if (!$this->hasRole(['super_admin', 'hr_admin'])) {
            $this->session->setFlashdata('error', 'Access Denied: Super Admin privileges required.');
            return redirect()->to(site_url('dashboard'));
        }

        // Increase limits for database export
        @set_time_limit(300);
        @ini_set('memory_limit', '512M');

        $db     = \Config\Database::connect();
        $dbName = $db->database;
        $tables = $db->listTables();

        $sql = "-- ==================================================================\n";
        $sql .= "-- ENTERPRISE HRMS DATABASE SNAPSHOT BACKUP\n";
        $sql .= "-- Database: `{$dbName}`\n";
        $sql .= "-- Generated: " . date('Y-m-d H:i:s T') . "\n";
        $sql .= "-- Server Version: " . $db->getVersion() . "\n";
        $sql .= "-- Generated by: " . ($this->currentUser['email'] ?? 'Super Admin') . "\n";
        $sql .= "-- ==================================================================\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n";
        $sql .= "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n";
        $sql .= "SET NAMES utf8mb4;\n\n";

        foreach ($tables as $table) {
            // Drop & Create statement
            $sql .= "-- ------------------------------------------------------------------\n";
            $sql .= "-- Table structure for `{$table}`\n";
            $sql .= "-- ------------------------------------------------------------------\n";
            $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";

            $createRow = $db->query("SHOW CREATE TABLE `{$table}`")->getRowArray();
            if (isset($createRow['Create Table'])) {
                $sql .= $createRow['Create Table'] . ";\n\n";
            }

            // Export Rows
            $rows = $db->table($table)->get()->getResultArray();
            if (!empty($rows)) {
                $sql .= "-- Dumping data for table `{$table}` (" . count($rows) . " rows)\n";

                // Chunk inserts
                $chunks = array_chunk($rows, 50);
                foreach ($chunks as $chunk) {
                    $fields = array_keys($chunk[0]);
                    $fieldList = '`' . implode('`, `', $fields) . '`';

                    $valuesList = [];
                    foreach ($chunk as $row) {
                        $escapedVals = [];
                        foreach ($row as $val) {
                            if ($val === null) {
                                $escapedVals[] = 'NULL';
                            } elseif (is_numeric($val) && !is_string($val)) {
                                $escapedVals[] = $val;
                            } else {
                                $escapedVals[] = "'" . addslashes((string)$val) . "'";
                            }
                        }
                        $valuesList[] = '(' . implode(', ', $escapedVals) . ')';
                    }

                    $sql .= "INSERT INTO `{$table}` ({$fieldList}) VALUES\n" . implode(",\n", $valuesList) . ";\n";
                }
                $sql .= "\n";
            }
        }

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
        $sql .= "-- Snapshot completed at " . date('Y-m-d H:i:s') . "\n";

        $filename = "hrms_backup_{$dbName}_" . date('Ymd_His') . '.sql';

        $this->logAudit('DATABASE_BACKUP', 'system', "Generated full database dump {$filename} (" . count($tables) . " tables)");

        return $this->response
                    ->setHeader('Content-Type', 'application/sql; charset=utf-8')
                    ->setHeader('Content-Disposition', 'attachment; filename="' . $filename . '"')
                    ->setBody($sql);
    }
}
